# Generated by Django 4.0.4 on 2022-09-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back']},
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, help_text='Введіть кінець строку статусу', null=True, verbose_name='Дата закінчення статусу'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='imprint',
            field=models.CharField(blank=True, help_text='Видавництво та рік випуску', max_length=200, null=True, verbose_name='Видавництво'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Технічне обслуговування'), ('o', 'On loan'), ('a', 'Доступний'), ('r', 'Зарезервований')], default='m', help_text='Змінити статус екземпляра', max_length=1),
        ),
    ]
