# Generated by Django 4.1 on 2022-09-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_catalog_library_rack_delete_bookrent_delete_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rack',
        ),
    ]
