# Generated by Django 4.0.4 on 2022-05-25 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bookinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active', models.BooleanField()),
                ('book_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bookinstance')),
            ],
        ),
    ]
