# Generated by Django 4.0.4 on 2022-05-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bookinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_visitor', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('books', models.ManyToManyField(to='core.book')),
            ],
        ),
    ]
