# Generated by Django 4.0.5 on 2022-09-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_catalog_library_rack_delete_bookrent_delete_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.DeleteModel(
            name='Rack',
        ),
    ]
