# Generated by Django 4.0.4 on 2022-06-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_visitor_book_number_bookrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='number',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
