# Generated by Django 4.0.4 on 2022-06-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_visitor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='ISBN',
            field=models.CharField(default="I don't know what it is", max_length=13),
        ),
        migrations.AddField(
            model_name='visitor',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='order',
            field=models.CharField(default='this is my order', max_length=200),
        ),
    ]
