# Generated by Django 4.0.5 on 2022-09-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bookinstance_date_lending_bookinstance_date_messege_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='date_lending',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='date_messege',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='format_book',
            field=models.IntegerField(choices=[(1, 'paper'), (2, 'ebook'), (3, 'magazine'), (4, 'audio')]),
        ),
    ]
