# Generated by Django 4.0.5 on 2022-09-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_bookinstance_date_lending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Технічне обслуговування'), ('o', 'Видана'), ('a', 'Доступна'), ('r', 'Зарезервована')], default='m', help_text='Змінити статус екземпляра', max_length=1),
        ),
    ]
