# Generated by Django 4.0.4 on 2022-06-13 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_visitor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrent',
            name='date_off',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
