# Generated by Django 4.1 on 2022-09-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bookinstance_isbn_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Технічне обслуговування'), ('o', 'Видана'), ('a', 'Доступна'), ('r', 'Зарезервована')], default='a', help_text='Змінити статус екземпляра', max_length=1),
        ),
    ]
