# Generated by Django 4.0.4 on 2022-06-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bookrent_date_off_alter_visitor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='ISBN',
        ),
    ]
