# Generated by Django 4.1 on 2022-09-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='format_book',
            field=models.IntegerField(choices=[(1, 'paper'), (2, 'ebook'), (3, 'magazin'), (4, 'audio')]),
        ),
    ]
