# Generated by Django 4.0.4 on 2022-09-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Технічне обслуговування'), ('o', 'Видана'), ('a', 'Доступна'), ('r', 'Зарезервована')], default='m', max_length=1),
        ),
    ]
