# Generated by Django 4.1 on 2022-09-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bookinstance_format_book'),
        ('core', '0009_alter_bookinstance_status'),
    ]

    operations = [
    ]
