# Generated by Django 4.1 on 2022-10-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20220926_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Автори'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book'], 'verbose_name': 'Екземпляр книги', 'verbose_name_plural': 'Екземпляри книг'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title'], 'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='format_book',
            field=models.IntegerField(choices=[(1, 'paper'), (2, 'ebook'), (3, 'magazine'), (4, 'audio')], verbose_name='Формат:'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Технічне обслуговування'), ('o', 'Видана'), ('a', 'Доступна'), ('r', 'Зарезервована')], default='m', max_length=1, verbose_name='Статус:'),
        ),
    ]
