# Generated by Django 4.1 on 2022-11-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book', 'id'], 'verbose_name': 'Екземпляр книги', 'verbose_name_plural': 'Екземпляри книг'},
        ),
    ]
