# Generated by Django 4.0.5 on 2022-09-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_bookinstance_date_lending_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rack',
            name='number_rack',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='number_shell',
        ),
        migrations.AddField(
            model_name='rack',
            name='books',
            field=models.ManyToManyField(to='core.bookinstance'),
        ),
    ]
