# Generated by Django 4.0.5 on 2022-09-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_rack_number_rack_remove_rack_number_shell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
