# Generated by Django 4.1 on 2022-09-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bookinstance_format_book'),
        ('warehouse', '0003_rack_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='books',
            field=models.ManyToManyField(blank=True, to='core.bookinstance'),
        ),
    ]
