# Generated by Django 4.0.4 on 2022-09-18 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_bookinstance_status'),
        ('warehouse', '0003_rack_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseBookInstanse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bookinstance')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.rack')),
            ],
        ),
    ]
