# Generated by Django 4.0.5 on 2022-09-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_bookinstance_status'),
        ('warehouse', '0003_rack_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='books',
            field=models.ManyToManyField(blank=True, to='core.bookinstance'),
        ),
    ]
