# Generated by Django 4.0.4 on 2022-09-22 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_warehousebookinstanse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WarehouseBookInstanse',
        ),
    ]
