# Generated by Django 4.1 on 2022-09-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_rack_books'),
        ('warehouse', '0005_delete_warehousebookinstanse'),
    ]

    operations = [
    ]
