# Generated by Django 4.1 on 2022-10-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_merge_20220926_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rack',
            options={'ordering': ['title'], 'verbose_name': 'Поличка книг', 'verbose_name_plural': 'Полички книг'},
        ),
    ]
