# Generated by Django 4.1 on 2022-09-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bookinstance_isbn_alter_bookinstance_status'),
        ('library_reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstenceRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_rent_date', models.DateField()),
                ('return_date', models.DateField(auto_now_add=True)),
                ('title_book', models.ManyToManyField(to='core.bookinstance')),
            ],
        ),
    ]
