# Generated by Django 4.1 on 2022-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_reception', '0002_bookinstencerent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstencerent',
            name='return_date',
            field=models.DateField(),
        ),
    ]
