# Generated by Django 4.1 on 2022-09-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bookinstance_isbn_alter_bookinstance_status'),
        ('library_reception', '0003_alter_bookinstencerent_return_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstenceRent',
            new_name='BookInstanceRent',
        ),
    ]
