# Generated by Django 4.1 on 2022-09-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_reception', '0004_rename_bookinstencerent_bookinstancerent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstancerent',
            old_name='title_book',
            new_name='book',
        ),
    ]
