# Generated by Django 4.1 on 2022-09-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_librarian_options_alter_member_options'),
        ('core', '0008_alter_bookinstance_status'),
        ('library_reception', '0006_rename_book_bookinstancerent_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookreservation',
        ),
        migrations.DeleteModel(
            name='LibraryCard',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.AddField(
            model_name='bookinstancerent',
            name='librarian',
            field=models.ManyToManyField(to='visitors.librarian', verbose_name='Книгу видав:'),
        ),
        migrations.AddField(
            model_name='bookinstancerent',
            name='member',
            field=models.ManyToManyField(to='visitors.member', verbose_name='Книгу отримав'),
        ),
        migrations.AlterField(
            model_name='bookinstancerent',
            name='books',
            field=models.ManyToManyField(to='core.bookinstance', verbose_name='Назва книги:'),
        ),
    ]
