# Generated by Django 4.1 on 2022-09-21 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_librarian_options_alter_member_options'),
        ('core', '0008_alter_bookinstance_status'),
        ('library_reception', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInstanceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(related_name='bookItem', to='core.bookinstance', verbose_name='Назва книги:')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.member', verbose_name='Книгу замовив')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bookinstance', verbose_name='Статус книги')),
            ],
        ),
    ]
