# Generated by Django 4.1 on 2022-10-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_reception', '0011_remove_bookinstanceorder_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstanceorder',
            options={'ordering': ['member'], 'verbose_name': 'Замовлення книги', 'verbose_name_plural': 'Замовлення книг'},
        ),
        migrations.AlterModelOptions(
            name='bookinstancerent',
            options={'ordering': ['member'], 'verbose_name': 'Оренда книги', 'verbose_name_plural': 'Оренда книг'},
        ),
        migrations.AddField(
            model_name='bookinstanceorder',
            name='moment_reserve',
            field=models.DateTimeField(auto_now=True, verbose_name='Момент резервування'),
        ),
    ]
