# Generated by Django 4.1 on 2022-11-05 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_alter_librarian_options_alter_member_options'),
        ('core', '0012_alter_bookinstance_options'),
        ('library_reception', '0012_alter_bookinstanceorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstanceorder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='bookinstancerent',
            options={'ordering': ['-id'], 'verbose_name': 'Оренда книги', 'verbose_name_plural': 'Оренда книг'},
        ),
        migrations.AlterField(
            model_name='bookinstanceorder',
            name='books',
            field=models.ManyToManyField(to='core.bookinstance'),
        ),
        migrations.AlterField(
            model_name='bookinstanceorder',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.member'),
        ),
        migrations.AlterField(
            model_name='bookinstanceorder',
            name='moment_reserve',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookinstancerent',
            name='books',
            field=models.ManyToManyField(to='core.bookinstance'),
        ),
        migrations.AlterField(
            model_name='bookinstancerent',
            name='librarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.librarian'),
        ),
        migrations.AlterField(
            model_name='bookinstancerent',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.member'),
        ),
    ]
