# Generated by Django 4.1 on 2022-11-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_alter_librarian_options_alter_member_options'),
        ('core', '0012_alter_bookinstance_options'),
        ('library_reception', '0013_alter_bookinstanceorder_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstanceRent',
            new_name='BookLending',
        ),
        migrations.RenameModel(
            old_name='BookInstanceOrder',
            new_name='BookReservation',
        ),
        migrations.AlterModelOptions(
            name='bookreservation',
            options={'ordering': ['-id'], 'verbose_name': 'Замовлення книги', 'verbose_name_plural': 'Замовлення книг'},
        ),
    ]
