# Generated by Django 4.0.5 on 2022-09-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarian',
            options={'verbose_name': 'Librarian', 'verbose_name_plural': 'Librarians'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
    ]
