# Generated by Django 4.1 on 2022-10-11 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_librarian_options_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarian',
            options={'verbose_name': 'Бібліотекар', 'verbose_name_plural': 'Бібліотекарі'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Користувач бібліотеки', 'verbose_name_plural': 'Користувачи бібліотеки'},
        ),
    ]
